name: 'actions-goveralls'
description: 'Coveralls GitHub Action with Go integration powered by mattn/goveralls'
author: 'Ichinose Shogo'
inputs:
  github-token:
    description: Coveralls uses this token to verify the posted coverage data on the repo and create a new check based on the results.
    required: true
    default: '${{ github.token }}'
  path-to-profile:
    description: a path to your cover profile.
    required: false
    default: ''
  parallel:
    description: 'Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.'
    required: false
    default: false
  parallel-finished:
    description: 'Set to true for the last action when using "parallel: true".'
    required: false
    default: false
  job-number:
    description: "job number"
    required: false
    default: '${{ strategy.job-index }}'

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'green'
  icon: 'percent'
