name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: action

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "action/go.mod"
      - run: go version

      - name: Set up the action
        run: |
          make all      # build goveralls binaries
        working-directory: action

      - name: archive
        run: tar czvf action.tar.gz action
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: action
          path: ./action.tar.gz

  # run tests with Go that supports go.mod
  test:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-26
          - macos-14 # for arm64
          - macos-15-intel # for x64
          - windows-11-arm # for arm64
          - windows-2025
          - windows-2022
        go:
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
          - "oldstable"
          - "stable"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}
      - run: go version

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: action
      - name: extract
        run: tar xzvf action.tar.gz
      - name: send coverage
        uses: ./action/
        with:
          parallel: true
          flag-name: ${{ runner.os }}-Go-${{ matrix.go }}
          shallow: true

  finish:
    needs:
      - build
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: action
      - name: extract
        run: tar xzvf action.tar.gz
      - name: finalize parallel build
        uses: ./action/
        with:
          parallel-finished: true
          shallow: true
